# Generated by Django 3.2.7 on 2021-10-03 17:16

from django.db import migrations, models

from ugc.models import DeepLinking


def create_data(apps, schema_editor):
    DeepLinking(
        referral_id='12345678',
        user_id='001',
        user_name='Vova',
    ).save()
    DeepLinking(
        referral_id='8934043',
        user_id='005',
        user_name='Ivan',
    ).save()
    DeepLinking(
        referral_id='2409440',
        user_id='015',
        user_name='Sergey',
    ).save()
    DeepLinking(
        referral_id='87654321',
        user_id='007',
        user_name='Vlad',
    ).save()
    DeepLinking(
        referral_id='65432187',
        user_id='010',
        user_name='Nazar',
    ).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=8, verbose_name='referral id')),
                ('user_id', models.CharField(max_length=8, unique=True, verbose_name='user id')),
                ('user_name', models.TextField(verbose_name='user name')),
            ],
            options={
                'verbose_name': 'Идентификатори',
                'verbose_name_plural': 'Идентификатор',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID користувача в телеграмі')),
                ('name', models.TextField(verbose_name='Ім`я користувача')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Профілі',
            },
        ),
        migrations.RunPython(create_data),
    ]
